// Generated by scripts/generate-icon-font.mjs. Do not edit by hand.
export const APP_ICON_GLYPHS = {
  "home": "\uE001",
  "account": "\uE002",
  "storage": "\uE003",
  "backup": "\uE004",
  "history": "\uE005",
  "file-restore": "\uE006",
  "shield": "\uE007",
  "modules": "\uE008",
  "info": "\uE009",
  "chevron-right": "\uE00A",
  "appointment": "\uE00B",
  "customer": "\uE00C",
  "projects": "\uE00D",
  "inventory": "\uE00E",
  "calendar": "\uE00F",
  "reports": "\uE010",
  "data": "\uE011",
} as const;

export type AppIconName = keyof typeof APP_ICON_GLYPHS;
