// Generated by scripts/generate-icon-font.mjs. Do not edit by hand.
export const APP_ICON_GLYPHS = {
  "home": "\uE001",
  "account": "\uE002",
  "storage": "\uE003",
  "backup": "\uE004",
  "history": "\uE005",
  "file-restore": "\uE006",
  "shield": "\uE007",
  "modules": "\uE008",
  "info": "\uE009",
  "chevron-right": "\uE00A",
} as const;

export type AppIconName = keyof typeof APP_ICON_GLYPHS;
